
import javax.swing.JTextArea;
import javax.swing.Timer;

/*
 * This is the interface of the server and calls the rest of the classes. It is
 * created in the run class.
 */
public class GUI extends javax.swing.JFrame {
    
    
    /**
     * Creates new form GUI
     */
    public Server server;
    public boolean isServerRunning = false;
    Timer currentTimeTimer;
    Timer updateInfoPanelTimer;
    ShareMutexMonitor mtx = new ShareMutexMonitor();
    public GUI(){
        this.server = new Server("localhost", 8189, this, this.mtx);
        this.currentTimeTimer = new Timer(500,(e) -> {
            mtx.enterCrit();
            serverTime_textField.setText(server.getCurrentServerTime());
            mtx.exitCrit();
        });
        this.updateInfoPanelTimer = new Timer(100,(e) -> {
            mtx.enterCrit();
            shareInfo_textArea.setText(StockMarket.status());
            mtx.exitCrit();
        });
        initComponents();
        this.currentTimeTimer.start();
        this.updateInfoPanelTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        serverLog_textArea = new javax.swing.JTextArea();
        startServer_button = new javax.swing.JButton();
        stopServer_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        shareInfo_textArea = new javax.swing.JTextArea();
        serverTime_textField = new javax.swing.JTextField();
        serverLog_label = new javax.swing.JLabel();
        shareInfo_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverLog_textArea.setEditable(false);
        serverLog_textArea.setColumns(20);
        serverLog_textArea.setLineWrap(true);
        serverLog_textArea.setRows(5);
        jScrollPane1.setViewportView(serverLog_textArea);

        startServer_button.setText("Start Server");
        startServer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServer_buttonActionPerformed(evt);
            }
        });

        stopServer_button.setText("Stop Server");
        stopServer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopServer_buttonActionPerformed(evt);
            }
        });

        shareInfo_textArea.setEditable(false);
        shareInfo_textArea.setColumns(20);
        shareInfo_textArea.setRows(5);
        shareInfo_textArea.setToolTipText("");
        jScrollPane2.setViewportView(shareInfo_textArea);
        shareInfo_textArea.getAccessibleContext().setAccessibleParent(jScrollPane1);

        serverTime_textField.setEditable(false);
        serverTime_textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serverTime_textField.setText("Time");
        serverTime_textField.setBorder(null);
        serverTime_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverTime_textFieldActionPerformed(evt);
            }
        });

        serverLog_label.setText("Server Log");

        shareInfo_label.setText("Share Information");

        jLabel1.setText("Server Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverLog_label)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(serverTime_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(startServer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(stopServer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shareInfo_label))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shareInfo_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serverLog_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startServer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stopServer_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(serverTime_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverTime_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverTime_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverTime_textFieldActionPerformed

    private void startServer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServer_buttonActionPerformed
        // start server and assign gui to server to use
        if(!isServerRunning){
            try {
                server = new Server("localhost", 8189, this, this.mtx);
                server.execute();
                isServerRunning = true; 
            } catch (Exception e) {
                isServerRunning = false;
            }
            
        }else{
            this.getServerLog_textArea().append("Server start failed." + "\n");
        }
        
        
    }//GEN-LAST:event_startServer_buttonActionPerformed

    private void stopServer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopServer_buttonActionPerformed
        // stop server and print
        if(isServerRunning){
            try {
                server.stop();
                server.cancel(true);
                this.isServerRunning = false;
            } catch (Exception e) {
                this.isServerRunning = true;
            }
        }

    }//GEN-LAST:event_stopServer_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel serverLog_label;
    private javax.swing.JTextArea serverLog_textArea;
    private javax.swing.JTextField serverTime_textField;
    private javax.swing.JLabel shareInfo_label;
    private javax.swing.JTextArea shareInfo_textArea;
    private javax.swing.JButton startServer_button;
    private javax.swing.JButton stopServer_button;
    // End of variables declaration//GEN-END:variables

    public JTextArea getServerLog_textArea() {
        return serverLog_textArea;
    }
}
